### ISSUE TITLE
Add mouseover info icons

### ISSUE THREAD

**Issue by vimwitch** [Unirep/create-unirep-app#11]
- [ ] - What does joining mean?
- [ ] - Epoch
- [ ] - Epoch key
- [ ] - Graffiti
- [ ] - Graffiti preimage
- [ ]  - request
- [ ]  - transition
- [ ] - prove
- [ ] - current rep
- [ ] - received rep

**Comment by ChialiTsai** [comment]
can take some copy from here: https://unirep.io/docs/protocol/epoch-key
