### ISSUE TITLE
Add loading stages

### ISSUE THREAD

**Issue by vimwitch** [Unirep/create-unirep-app#12]
The loading button text should change as the internal tasks are completed.

e.g. `Downloading keys...Generating proof...Waiting for tx`

This could also be accomplished with a log style output.

**Comment by ChialiTsai** [comment]
@vimwitch or @kittybest can you help @CJ-Rose how to fetching this this one?

**Comment by ChialiT** [comment]
this issue seems already completed? @CJ-Rose

**Comment by ChialiT** [comment]
Closing this issue for overhaul create unirep app dx visit
