### ISSUE TITLE
Prove graffiti bug

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/create-unirep-app#22]
Definition:
```ts
graffiti = hash1([graffitiPreImage])
```
In request reputation, it takes `preImage` as input but send `graffiti` to relayer
https://github.com/Unirep/create-unirep-app/blob/09235a9349bb00bbb81c5c64c49beb9992ce9989/packages/frontend/src/contexts/User.js#L91-L93

But in prove reputation, it should take `preImage` in `genProveReputationProof` not the `hash(preImage)`
https://github.com/Unirep/create-unirep-app/blob/09235a9349bb00bbb81c5c64c49beb9992ce9989/packages/frontend/src/contexts/User.js#L130-L134

and like request reputation
https://github.com/Unirep/create-unirep-app/blob/09235a9349bb00bbb81c5c64c49beb9992ce9989/packages/frontend/src/Home.jsx#L128-L133
The default value should not be `0`
or it will send `hash(0)` to the router
so it should be
```js
            await userContext.requestReputation(
              reqRep.posRep ?? 0,
              reqRep.negRep ?? 0,
              reqRep.graffitiPreimage,
              reqRep.nonce ?? 0
            )
```
and let `requestReputation` to check
```js
const graffiti = graffitiPreImage ? hash1([graffitiPreImage]) : 0
```

**Comment by vimwitch** [comment]
Closed by #23
