### ISSUE TITLE
Experience/test how to build simple app

### ISSUE THREAD

**Issue by ChialiT** [Unirep/create-unirep-app#3]
Part of the onboarding exercise.

Please try to build a simple app using only create-unirep-app and documentation.

Expected output:
This is to see and understand when a developer fork our app, what challenges they will be facing, and what needs to be fixed.
- a list of pain point/challenges when you build the simple app
- missing documentation
- anything you think can help our developer experience.

**Comment by CJ-Rose** [comment]
### **DOCUMENTATION**
- Expand description of project
    - Define terms (attester, transition, rep)
    - Purpose (detail what user can expect to demonstrate)
    - Make clear that building the project creates an example attester, interacting with FE as an app user
    - Is this experience intended only to demonstrate these basic functions, or do we want to include ideas/instruction on how a user can customize their attester?

- Expand description of build steps
    - What is the Hardhat node doing? It deploys 20(?) contracts to different addresses, then makes calls to one of those contracts every 10(?) seconds… I have no idea what is happening here ; /
    - Basic description of what the relayer is doing would be helpful
    - Intro to what the user can expect to demo on the front end

- Link to docs (currently only to unirep repo)

- Individual package READMEs
    - Is contracts folder README redundant? Starting node and deploying contract are already done from project root
    - Frontend and relay are empty


### **UI**
- Landing page (join button)
    - Can this page display anything else about the app that’s being joined? (If customized by the user)
    - At least include text about what joining means
    - Display info about what is happening under the hood while loading?

- Description of terms and actions
    - Define epoch, epoch key (add dropdown to choose 0-2), graffiti, graffiti preimage
    - Define request, transition, prove… what are we asking for when we interact with these buttons
    - Display info about what is happening under the hood while processing?
    - What is the difference between current rep and received rep?

- Clarify user flow
    - Organize into visually obvious sections; 1: epoch / rep status, 2: inputs for request, 3: inputs for proof
    - It is unclear what is supposed to happen with transition
    - Clear input fields after they are submitted
    - Add button(?) to clear display of public signal and proof validation


### **ISSUES**
- Build error on yarn install:
	( I am able to execute all of the following steps and use the app from the frontend, but wondering how this error might be affecting usage / how to resolve it)
<img width="1143" alt="Screen Shot 2022-11-28 at 4 54 12 PM" src="https://user-images.githubusercontent.com/79813968/204636595-15029445-82d3-40de-9774-0031acb05efc.png">
<img width="988" alt="Screen Shot 2022-11-29 at 9 38 08 AM" src="https://user-images.githubusercontent.com/79813968/204636865-134de5ed-c41f-41b9-8c1a-1071c902d38a.png">

- Error on transition:
    - An error msg appears in the UI but is gone too quickly to read
    - Not sure what user is passing or expecting from transition, error msg could be used to clarify
    
<img width="1354" alt="Screen Shot 2022-11-29 at 12 40 46 PM" src="https://user-images.githubusercontent.com/79813968/204637069-192c98b8-0592-44b4-be61-ffe647f75e64.png">


- Proof displays true even when proving more rep than shown in UI

- Was able to prove with graffiti preimage as a number, but not a username:
<img width="1354" alt="Screen Shot 2022-11-29 at 12 51 12 PM" src="https://user-images.githubusercontent.com/79813968/204637152-95bbebac-75d6-4023-812b-9ecbcea492bd.png">

**Comment by ChialiTsai** [comment]
the UI section here was from this "create-unirep-app" right?
I haven't run this on myself yet...XD

**Comment by ChialiTsai** [comment]
https://github.com/vimwitch/canon

reference

**Comment by ChialiTsai** [comment]
the issue is on hold til the 2.0.0-alpha-3 release. Targetting at Dec/5~
