### ISSUE TITLE
[Frontend] remove some fields

### ISSUE THREAD

**Issue by kittybest** [Unirep/create-unirep-app#31]
the timestamp field is not changeable, remove it.
the graffiti field is no longer exists, remove it.
do not allow negative value in data field.

**Comment by vimwitch** [comment]
In beta 3 there are no more timestamps, instead the first 48 bits of the replacement field stores the timestamp data. There's a working copy of this repo [here](https://demo.unirep.io), try setting one of the replacement fields and it will parse the data for you

**Comment by vimwitch** [comment]
This is how it looks if i receive data `100` in a replacement field, 6 is the timestamp value (in the leading 48 bits). We don't use a timestamp anymore, it's just an attestation count

<img width="341" alt="image" src="https://user-images.githubusercontent.com/631020/232694429-0f20c33a-2a45-44d0-8487-c9e1b97c13bb.png">

**Comment by kittybest** [comment]
> In beta 3 there are no more timestamps, instead the first 48 bits of the replacement field stores the timestamp data. There's a working copy of this repo [here](https://demo.unirep.io), try setting one of the replacement fields and it will parse the data for you

So do I need to migrate the whole repo to beta-3 protocol?
or I just modify the current main branch first? I only want to slightly modify the UI, for Antony to do the workshop next week.

**Comment by vimwitch** [comment]
I think we should support beta-3 for the workshop. Removing the epoch seal proof is a pretty important optimization, plus the UST proof is smaller now

**Comment by kittybest** [comment]
@vimwitch I just saw your beta-3 working branch, so I update the fe UI after you finish the beta-3 branch?

**Comment by vimwitch** [comment]
Well, it doesn't have any of the typescript/circuit changes, it's almost a fork of the current repo.
