### ISSUE TITLE
[circuits] add replacement data proof

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/create-unirep-app#50]
now [dataProof.circom](https://github.com/Unirep/create-unirep-app/blob/main/packages/circuits/circuits/dataProof.circom) only proves sum field data, but we can prove [replacement data](https://developer.unirep.io/docs/protocol/data#replacement-field) too.

we can prove like `input[x] === data[x]` in replacement data field

**Comment by s-ekai** [comment]
@vivianjeng 

Hi, I have a question.

If I were to create inputs for Data4 and Data5 using the Prove Data form, should I input the data from the Replacement field directly, or is it assumed that I should only input the data with the format data(number)? (Let's assume that the Replacement field consists of data and an index.)

If it's assumed that I should input the Replacement field data directly into the input, I thought it might be easy to check it in a format like `input[x] === data[x]`.

Also, should I impose a constraint in circom that the value of Replacement field data must be greater than the value entered in Prove Data?

I apologize if these questions are off track.

I am currently envisioning the following code:

```
template DataProof(STATE_TREE_DEPTH, FIELD_COUNT, SUM_FIELD_COUNT) {

    // State tree leaf: Identity & user state root
    signal input identity_secret;
    // State tree
    signal input state_tree_indexes[STATE_TREE_DEPTH];
    signal input state_tree_elements[STATE_TREE_DEPTH];
    signal input attester_id;
    signal input data[FIELD_COUNT];
    signal output state_tree_root;
    signal input epoch;

    // Prove values
    signal input value[FIELD_COUNT];

    /* 1. Check if user exists in the State Tree */

    // Compute state tree root
    component leaf_hasher = StateTreeLeaf(FIELD_COUNT);
    leaf_hasher.identity_secret <== identity_secret;
    leaf_hasher.attester_id <== attester_id;
    leaf_hasher.epoch <== epoch;
    for (var x = 0; x < FIELD_COUNT; x++) {
      leaf_hasher.data[x] <== data[x];
    }

    component merkletree = MerkleTreeInclusionProof(STATE_TREE_DEPTH);
    merkletree.leaf <== leaf_hasher.out;
    for (var i = 0; i < STATE_TREE_DEPTH; i++) {
        merkletree.path_index[i] <== state_tree_indexes[i];
        merkletree.path_elements[i] <== state_tree_elements[i];
    }
    state_tree_root <== merkletree.root;

    /* End of check 1 */

     /* 2. Check if user data more than given value */
    component get[SUM_FIELD_COUNT];
    for (var x = 0; x < SUM_FIELD_COUNT; x++) {
        get[x] = GreaterEqThan(252);
        get[x].in[0] <== data[x];
        get[x].in[1] <== value[x];
        get[x].out === 1;
    }
    /* End of check 2 */

    /* 3. Check if replacement data matches given value */
    component equal_check[FIELD_COUNT - SUM_FIELD_COUNT];
    for (var x = 0; x < (FIELD_COUNT - SUM_FIELD_COUNT); x++) {
        equal_check[x] = IsEqual();
        equal_check[x].in[0] <== data[SUM_FIELD_COUNT + x];
        equal_check[x].in[1] <== value[SUM_FIELD_COUNT + x];
        equal_check[x].out === 1;
    }
    // /* End of check 3 */
}
```

**Comment by vivianjeng** [comment]
Hi @s-ekai 
Thank you for clarifying this issue, I didn't think this really carefully.

I think you are right, we don't have to input the value in replacement field (since we can take the `data[FIELD_COUNT]` itself)
but it would be good that we can **optionally** prove the replacement field

e.g. we can input
```circom
signal input selectors[FIELD_COUNT - SUM_FIELD_COUNT];
```
if `selectors[i] == 1`, we reveal the `data[SUM_FIELD_COUNT+i]`

and actually the replacement data is not 254 bits: [replacement-field](https://developer.unirep.io/docs/protocol/data#replacement-field)

we can encode the output signal here as
- 205 bits data (upper bits)
- 1 bits selector (lower bits)
or
- 1 bits selector (upper bits)
- 205 bits data (lower bits)

To implement this you might need to use [`ExtractBits`](https://github.com/Unirep/Unirep/blob/91b479f0cb5fea888ad2a04c04bb35815cf5c228/packages/circuits/circuits/bigComparators.circom#L7) to get the upper bits data from `data[SUM_FIELD_COUNT+i]`
and shift the bits like
```circom
extractor[i] = ExtractBits(REPL_NONCE_BITS, 253-REPL_NONCE_BITS);
extractor[i].in <== data[SUM_FIELD_COUNT+i];

signal output replacement_data[i] <== extractor[i].upper * 2 + selectors[i];
// or signal output replacement_data[i] <== selectors[i] * (2**REPL_NONCE_BITS) + extractor[i].upper;
```

(and the frontend can parse this data to get the revealed data)

**Comment by vivianjeng** [comment]
> Also, should I impose a constraint in circom that the value of Replacement field data must be greater than the value entered in Prove Data?

We only need to prove the `IsEqual()` in replacement data field
since it is updated by replacement 
so the latest one might be smaller than the previous one
(You can imagine It is used for data like string or hash value)

**Comment by vivianjeng** [comment]
Maybe you can use this in your PR https://github.com/Unirep/create-unirep-app/issues/49
It will make it easier to write circuits

**Comment by s-ekai** [comment]
@vivianjeng 

Thank you for your response. I appreciate it. 
I will carefully review the information you provided and work on creating a PR!

Before that, I will tackle the following issue:
https://github.com/Unirep/create-unirep-app/issues/49

**Comment by s-ekai** [comment]
I created PR to solve https://github.com/Unirep/create-unirep-app/issues/49
https://github.com/Unirep/create-unirep-app/pull/51

**Comment by s-ekai** [comment]
@vivianjeng 

I was surprised to find out that the replacement field isn't always 254 bits, as I had misunderstood. Thank you for the clarification.

However, I have a question. 

Doesn't the part of the replacement field that holds the index data actually store the number of times the data has been replaced? 

For example, if Data 4 has been updated 100 times and is updated once more (let's say to 10), shouldn't the 205 bits of data (upper bits) be set to 10, and the remaining index portion be set to 101? 

I had this impression after reading the following code:
https://github.com/Unirep/Unirep/blob/main/packages/contracts/contracts/Unirep.sol#L289

**Comment by vivianjeng** [comment]
> Doesn't the part of the replacement field that holds the index data actually store the number of times the data has been replaced?
> 
> For example, if Data 4 has been updated 100 times and is updated once more (let's say to 10), shouldn't the 205 bits of data (upper bits) be set to 10, and the remaining index portion be set to 101?

Hi @s-ekai 
the index is used to count the number of replacement data (so either data 4 or data 5 in this case)
yes you are correct
the upper bits are `10` and the index (lower bits) are `101`
but not only data 4 but also data 5

**Comment by s-ekai** [comment]
@vivianjeng 

Thank you for the explanation. I understand it well.

I apologize for asking again, but I have a question. Why is it better to make the proof of the replacement field optional?

One reason I can think of is that it's difficult to input the correct value into the form for Provable Data. However, this can be resolved by automatically filling it in if it's stored as Provable Data. (I'm imagining something like an image.)

It's also possible to consider cases where the value of the replacement field is not attested in the first place, but this can be treated as zero, similar to the Addition field, to prove it.

<img width="1347" alt="スクリーンショット 2023-09-17 0 22 36" src="https://github.com/Unirep/create-unirep-app/assets/15361554/7a8b91e2-c1f7-46b8-803c-39f8332809a8">

**Comment by vivianjeng** [comment]
> I apologize for asking again, but I have a question. Why is it better to make the proof of the replacement field optional?

Hi @s-ekai 
If the replacement data is related to personal information (e.g. it could be the `username` of the user)
and sometimes the user doesn't want to prove data that is related to some case
(though `create-unirep-app` is just one example)

yeah we can make it not optional in the first step
and then we can improve it to be optional
I think both are fine 👍🏻

**Comment by vivianjeng** [comment]
@s-ekai I think the **prove data** can just be `4` and `5` in the right column
since it is attested `4` and `5`
we should not consider the data index

**Comment by s-ekai** [comment]
@vivianjeng 

Thank you for your response! It's very informative. I'm also planning to take a look at the code of create-unirep-app.

I went ahead and implemented it without making it optional first. When you have some time, I would appreciate it if you could review the following pull request:

https://github.com/Unirep/create-unirep-app/pull/55/files
