### ISSUE TITLE
Attestation isn't performing state root check

### ISSUE THREAD

**Issue by vimwitch** [Unirep/create-unirep-app#7]
[Here](https://github.com/Unirep/create-unirep-app/blob/main/packages/contracts/contracts/UnirepApp.sol#L35) in the application smart contract an attestation is made to an epoch key without proof that the epoch key has a state tree leaf. This causes a race condition in the `@unirep/core` package. Specifically an epoch key for a different epoch may be accidentally used.

[Here](https://github.com/Unirep/Unirep/blob/main/packages/core/src/UserState.ts#L214) we load attestations, we don't check the epoch key epoch. This is a separate problem to be fixed.

But I think the example application is a bad example. It should instead accept an epoch key proof and verify it on chain to prevent race conditions.

**Comment by vimwitch** [comment]
Even if we fix unirep/unirep#228 we'll have behaviour where users don't receive rep as they expect because of race conditions with epoch keys and the active epoch. e.g. i use my epoch key from epoch 1 and request 5 rep. The relay attests giving me 5 rep, but the relay attests in epoch 2. I now haven't received the rep because I don't control the epoch key I submitted in epoch 2, only in epoch 1.

**Comment by vimwitch** [comment]
@vivianjeng going to implement the behavior described above (accept a proof to get rep). Let me know if you have any objection.

**Comment by vivianjeng** [comment]
> @vivianjeng going to implement the behavior described above (accept a proof to get rep). Let me know if you have any objection.

I think it is okay to accept an epoch key proof to get rep
